import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getDatabase } from '../database'
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async () => {

  const mongoDb = await getDatabase();
  const getDirector = await mongoDb.db().collection("directors").find().toArray();
  const director = await JSON.parse(JSON.stringify(getDirector))
  console.log("test2", {director})

  return {
    props : {
      director: director,
    }
  }
}

type MyRectComponent={
  director: {
    _id: string,
    firstName: string,
    lastName: string,
  }[]
}

const Home: NextPage<MyRectComponent> = ({director}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {director.map((firstNames, index) => {
            return (
              <h1 className={styles.title} key={index}>
              Welcome to {firstNames.firstName}
              </h1>
              )
              })}
        </h1>
      </main>
    </div>
  )
}

export default Home
